### ISSUE TITLE
Store github tokens for user

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#15]
Let's store Github token (optinaly) in file `$HOME/.config/gitstrap/` to use it instead of `-token` argument.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#15](https://github.com/g4s8/gitstrap/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/gitstrap/issues/15#issuecomment-504030440))

@g4s8 This is what I know about this job in [CF7JL4282](https://www.0crat.com/p/CF7JL4282), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#15](https://github.com/g4s8/gitstrap/issues/15) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%2315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#15](https://github.com/g4s8/gitstrap/issues/15) assigned to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), here is [why](https://www.0crat.com/footprint/CF7JL4282/7bcdd3b1-4872-4691-919c-34567f2da1b0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vassilevsky[/z](https://www.0crat.com/u/vassilevsky) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vassilevsky** [comment]
@0crat wait for review

**Comment by 0crat** [comment]
> @0crat wait for review ([here](https://github.com/g4s8/gitstrap/issues/15#issuecomment-506844315))

@vassilevsky The impediment for [#15](https://github.com/g4s8/gitstrap/issues/15) was registered successfully by @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by vassilevsky** [comment]
@g4s8 The PR is merged. Please unpause this task.

**Comment by g4s8** [comment]
@vassilevsky thanks!

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by 0crat** [comment]
Job [#15](https://github.com/g4s8/gitstrap/issues/15) is not in the agenda of @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), can't inspect

**Comment by 0crat** [comment]
The job [#15](https://github.com/g4s8/gitstrap/issues/15) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.1`

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.4`
