### ISSUE TITLE
Contributor's Guide has no mention of commit message requirements

### ISSUE THREAD

**Issue by vassilevsky** [g4s8/gitstrap#18]
Problems described in https://github.com/g4s8/gitstrap/pull/17#issuecomment-504352216 are not in CONTRIBUTING.md 😢

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@vassilevsky it is described in Zerocracy policy, see https://www.zerocracy.com/policy.html#42

> All commit messages have links to issues

**Comment by vassilevsky** [comment]
@g4s8 Cool! This link should be added to the file then :)

**Comment by g4s8** [comment]
@vassilevsky thanks, done in https://github.com/g4s8/gitstrap/commit/86d5faa21a00ceec4cccfaab8a11e0cc67ebcb37

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#18` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
