### ISSUE TITLE
Go Meta Linter has been deprecated in favor of GolangCI-Lint

### ISSUE THREAD

**Issue by vassilevsky** [g4s8/gitstrap#23]
It is necessary to update all scripts that use `gometalinter`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#23](https://github.com/g4s8/gitstrap/issues/23) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#23](https://github.com/g4s8/gitstrap/issues/23); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#23](https://github.com/g4s8/gitstrap/issues/23); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#23](https://github.com/g4s8/gitstrap/issues/23) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CF7JL4282/a1de661d-3737-434e-ab50-000a2d3156fa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@vassilevsky it was fixed in https://github.com/g4s8/gitstrap/commit/3e1af5d7dd1d78d3b966cae8a2583856386c98d1 and https://github.com/g4s8/gitstrap/commit/3499e533adfeb3c7f12793c01bc104fdb1684eb4

**Comment by 0crat** [comment]
The job [#23](https://github.com/g4s8/gitstrap/issues/23) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
