### ISSUE TITLE
gitstrap.go:272-273: Extract name resolution logic and...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/gitstrap#25]
The puzzle `9-5fb1349f` from #9 has to be resolved: 

https://github.com/g4s8/gitstrap/blob/575aff71a87c97f74715324994894bae1fa13ade/gitstrap.go#L272-L273

The puzzle was created by @vassilevsky on 24-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#25](https://github.com/g4s8/gitstrap/issues/25) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#25](https://github.com/g4s8/gitstrap/issues/25) assigned to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), here is [why](https://www.0crat.com/footprint/CF7JL4282/dd5bb318-a00d-401b-91a7-1a8fd74f2e85); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vassilevsky[/z](https://www.0crat.com/u/vassilevsky) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vassilevsky** [comment]
@0crat wait for my availability

**Comment by 0crat** [comment]
> @0crat wait for my availability ([here](https://github.com/g4s8/gitstrap/issues/25#issuecomment-511543150))

@vassilevsky The impediment for [#25](https://github.com/g4s8/gitstrap/issues/25) was registered successfully by @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by g4s8** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/g4s8/gitstrap/issues/25#issuecomment-529784270))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) continued working on job [#25](https://github.com/g4s8/gitstrap/issues/25)

**Comment by 0crat** [comment]
The user @vassilevsky[/z](https://www.0crat.com/u/vassilevsky) resigned from [#25](https://github.com/g4s8/gitstrap/issues/25), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#25](https://github.com/g4s8/gitstrap/issues/25); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#25](https://github.com/g4s8/gitstrap/issues/25); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#25](https://github.com/g4s8/gitstrap/issues/25); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#25](https://github.com/g4s8/gitstrap/issues/25); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0pdd** [comment]
The puzzle `9-5fb1349f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#25](https://github.com/g4s8/gitstrap/issues/25) is now out of scope
