### ISSUE TITLE
Unable to create new repo

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#26]
Getting error on `create` command:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7c4f57]

goroutine 1 [running]:
github.com/g4s8/gitstrap.(*strapCtx).createRepo(0xc00000e6a0, 0xc000294fac, 0x4, 0xc000102300, 0xc0000974d0, 0xc0000dc600, 0xc000152000, 0x0)
        /home/g4s8/go/src/github.com/g4s8/gitstrap/gitstrap.go:189 +0xd7
github.com/g4s8/gitstrap.(*strapCreate).Run(0xc0000100a0, 0xc0000974d0, 0x7ffe67b7d12c, 0x6)
        /home/g4s8/go/src/github.com/g4s8/gitstrap/gitstrap.go:158 +0x2bd
main.main()
        /home/g4s8/projects/github.com/g4s8/gitstrap/cmd/gitstrap/main.go:54 +0x4a4
```

**Comment by 0crat** [comment]
Job [#26](https://github.com/g4s8/gitstrap/issues/26) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#26](https://github.com/g4s8/gitstrap/issues/26) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CF7JL4282/0f4406fc-ea9e-484a-ae94-e04b1795be46); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.5`

**Comment by 0crat** [comment]
The job [#26](https://github.com/g4s8/gitstrap/issues/26) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
