### ISSUE TITLE
Migrate to modules

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#29]
Let's migrate from go-1.10 to >=go-1.11 with modules support, see https://github.com/golang/go/wiki/Modules#migrating-to-modules for more details.

**Comment by 0crat** [comment]
Job [#29](https://github.com/g4s8/gitstrap/issues/29) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#29](https://github.com/g4s8/gitstrap/issues/29) assigned to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), here is [why](https://www.0crat.com/footprint/CF7JL4282/2b31d371-7a7d-4221-9d5b-2b00a055085b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-538664531))

@g4s8 The user @vassilevsky[/z](https://www.0crat.com/u/vassilevsky) resigned from [#29](https://github.com/g4s8/gitstrap/issues/29), please stop working. Reason for job resignation: Order was cancelled

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-538746761))

@mohamednizar This is what I know about this job in [CF7JL4282](https://www.0crat.com/p/CF7JL4282), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#29](https://github.com/g4s8/gitstrap/issues/29) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @vassilevsky[/z](https://www.0crat.com/u/vassilevsky): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%2329%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-544490614))

@g4s8 This is what I know about this job in [CF7JL4282](https://www.0crat.com/p/CF7JL4282), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#29](https://github.com/g4s8/gitstrap/issues/29) is [in scope](http://www.zerocracy.com/policy.html#14) for 17days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @vassilevsky[/z](https://www.0crat.com/u/vassilevsky): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%2329%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat assign @mohamednizar

**Comment by 0crat** [comment]
> @0crat assign @mohamednizar  ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-544581805))

@g4s8 The job [#29](https://github.com/g4s8/gitstrap/issues/29) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/CF7JL4282/108b2675-2d80-434e-8d33-991b164b3d3b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by mohamednizar** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-545046105))

@mohamednizar The impediment for [#29](https://github.com/g4s8/gitstrap/issues/29) was registered successfully by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-545209403))

@mohamednizar This is what I know about this job in [CF7JL4282](https://www.0crat.com/p/CF7JL4282), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#29](https://github.com/g4s8/gitstrap/issues/29) is [in scope](http://www.zerocracy.com/policy.html#14) for 19days
  * The role is `DEV`
  * The job is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @vassilevsky[/z](https://www.0crat.com/u/vassilevsky): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%2329%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by mohamednizar** [comment]
@g4s8 this is fixed and merged to the master. #30

**Comment by g4s8** [comment]
@mohamednizar thanks!

**Comment by mohamednizar** [comment]
@0crat status

**Comment by mohamednizar** [comment]
@0crat continue

**Comment by g4s8** [comment]
@0crat out

**Comment by mohamednizar** [comment]
@g4s8 do you any suggestions on this? Can’t we follow up this.

**Comment by g4s8** [comment]
@0crat out

**Comment by g4s8** [comment]
@mohamednizar it was https://www.rehttp.net/ issue - it failed to deliver webhook payload

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@b7e726625068, thread: pool-5-thread-1
org.hamcrest.MatcherAssert[20] java.lang.AssertionError: HTTP response status is not equal to 205:
202 Accepted [https://api.github.com/notifications]
Date: Tue, 29 Oct 2019 18:19:38 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 132
Server: GitHub.com
Status: 202 Accepted
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4705
X-RateLimit-Reset: 1572376612
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 801E:1411F:418FB9:4F9D89:5DB882BA

{"message":"Unread notifications couldn't be marked in a single request. Notifications are being marked as read in the background."}
Expected: HTTP response with status 205
     but: was <202 Accepted [https://api.github.com/notifications]
Date: Tue, 29 Oct 2019 18:19:38 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 132
Server: GitHub.com
Status: 202 Accepted
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4705
X-RateLimit-Reset: 1572376612
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 801E:1411F:418FB9:4F9D89:5DB882BA

{"message":"Unread notifications couldn't be marked in a single request. Notifications are being marked as read in the background."}>
```

[0.50.34](https://github.com/zerocracy/farm): Issue: g4s8/gitstrap#29, Action: `created`

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-546914741))

@mohamednizar This is what I know about this job in [CF7JL4282](https://www.0crat.com/p/CF7JL4282), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#29](https://github.com/g4s8/gitstrap/issues/29) is [in scope](http://www.zerocracy.com/policy.html#14) for 25days
  * The role is `DEV`
  * The job is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @vassilevsky[/z](https://www.0crat.com/u/vassilevsky): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%2329%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-546917583))

@mohamednizar @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) continued working on job [#29](https://github.com/g4s8/gitstrap/issues/29)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-547405998))

@g4s8 The job [#29](https://github.com/g4s8/gitstrap/issues/29) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/g4s8/gitstrap/issues/29#issuecomment-547567525))

@g4s8 Job `gh:g4s8/gitstrap#29` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
