### ISSUE TITLE
Enforce git commit message format

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#33]
Let's use same format for all git commit messages

**Comment by g4s8** [comment]
Done in https://github.com/g4s8/gitstrap/commit/c11b0b8d01523a395d12c469d8ebdd15371daec4 https://github.com/g4s8/gitstrap/commit/ee48fe2cb01f6bd77b58227c7661a3ddfc814d63

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#33` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
