### ISSUE TITLE
Generate link for create token with all preferences if the --token not provided

### ISSUE THREAD

**Issue by mohamednizar** [g4s8/gitstrap#34]
**Is your feature request related to a problem? Please describe.**
In a project directory if I ran the command `gitstrap create` without --token the 

'GitHub token neither given as a flag, nor found in /home/nizar/.config/gitstrap/github_token.tx'

**Describe the solution you'd like**
Instead of this error message , create link somthing like : 
https://github.com/settings/tokens/new?scopes=repo&description=gitstrap+on+99650139dc08+2019-11-08+1635
 for which is redirect the user and complete the --token registration, after that DEV can past the token which created and it will stored on config.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#34` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
