### ISSUE TITLE
Avoid "ssh-agent is not running. You should start it before running gitstrap and add correct ssh key to be able to access Github repo via git"

### ISSUE THREAD

**Issue by dgroup** [g4s8/gitstrap#36]
```cmd
ssh-agent is not running. You should start it before running gitstrap and add correct ssh key to be able to access Github repo via git
```
Is it possible to create a new repo without SSH keys configuration?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CF7JL4282) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by dgroup** [comment]
Fixed once all steps from https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent are completed, however, is it possible to avoid it?

**Comment by g4s8** [comment]
@dgroup It's needed to push `README`, `LICENSE` and other templates via `git://` protocol to new repository. But maybe it's possible to push using API key, I need to check it.

**Comment by g4s8** [comment]
@dgroup yes, it's possible to push using API key: https://stackoverflow.com/a/18936804/1723695. We'll need to use this `push` git remote `https://${username}:${token}@github.com/${repo}.git`, where:
 - `username` - Github user, API token owner
 - `token` - API token
 - `repo` - repository coordinates

when pushing initial commit.

(to performer: don't forget to replace it with default remote `push` URI after that: `git@github.com:${repo}.git`)

**Comment by 0crat** [comment]
Job [#36](https://github.com/g4s8/gitstrap/issues/36) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
The job [#36](https://github.com/g4s8/gitstrap/issues/36) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/CF7JL4282/39848d94-caa6-4e4c-95e6-3c45e0407066); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mohamednizar** [comment]
@0crat  wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/g4s8/gitstrap/issues/36#issuecomment-565722673))

@mohamednizar The impediment for [#36](https://github.com/g4s8/gitstrap/issues/36) was registered successfully by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by g4s8** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/g4s8/gitstrap/issues/36#issuecomment-569641505))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) continued working on job [#36](https://github.com/g4s8/gitstrap/issues/36)

**Comment by 0crat** [comment]
The user @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) resigned from [#36](https://github.com/g4s8/gitstrap/issues/36), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment]
The job [#36](https://github.com/g4s8/gitstrap/issues/36) assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), here is [why](https://www.0crat.com/footprint/CF7JL4282/fb0ed5b7-e7b0-4cef-8b46-697e4d919fba); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by GnusinPavel** [comment]
@dgroup you may try to clone repo using `git clone https://github.com/g4s8/gitstrap.git`. Please check this out

**Comment by GnusinPavel** [comment]
@0crat wait for #41

**Comment by 0crat** [comment]
> @0crat wait for #41  ([here](https://github.com/g4s8/gitstrap/issues/36#issuecomment-579990904))

@GnusinPavel The impediment for [#36](https://github.com/g4s8/gitstrap/issues/36) was registered successfully by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0crat** [comment]
The job [#36](https://github.com/g4s8/gitstrap/issues/36) assigned to @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry), here is [why](https://www.0crat.com/footprint/CF7JL4282/c444a344-9d86-4562-898e-2bedc10039dd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) resigned from [#36](https://github.com/g4s8/gitstrap/issues/36), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by g4s8** [comment]
@dgroup git is not used anymore, see #46
