### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#37]
Split main file `gitstrap.go` into few smaller files

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#37` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
The job [#37](https://github.com/g4s8/gitstrap/issues/37) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CF7JL4282/ff04359f-014b-46b2-a2d8-0179d762e5fe); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#40](https://github.com/g4s8/gitstrap/issues/40) is still not solved.

**Comment by g4s8** [comment]
Fixed in #39

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#40](https://github.com/g4s8/gitstrap/issues/40) is solved here.
