### ISSUE TITLE
Show version

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#4]
Show version info on `gitstrap -version`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#6](https://github.com/g4s8/gitstrap/issues/6) is still not solved.

**Comment by g4s8** [comment]
done

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#6](https://github.com/g4s8/gitstrap/issues/6) is solved here.
