### ISSUE TITLE
err.go:7-8: Move error handling to separate module and...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/gitstrap#40]
The puzzle `37-c7fbd670` from #37 has to be resolved: 

https://github.com/g4s8/gitstrap/blob/ece415dabcf86ec081665ea71399aa67d126f736/err.go#L7-L8

The puzzle was created by @g4s8 on 28-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `37-c7fbd670` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#40` is not assigned, can't get performer
