### ISSUE TITLE
Dead code with checking error

### ISSUE THREAD

**Issue by alex-semenyuk** [g4s8/gitstrap#44]
gitstrap\github\repo_delete.go

Check err on nil twice

```
        name, err := r.name()
	if err != nil {
		return err
	}
	owner := ctx.Owner()
	if err != nil {
		return err
	}
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@alex-semenyuk thanks

**Comment by 0crat** [comment]
The job [#44](https://github.com/g4s8/gitstrap/issues/44) assigned to @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry), here is [why](https://www.0crat.com/footprint/CF7JL4282/d43a2c40-0466-4bfa-a042-b8d13a03b7ca); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) resigned from [#44](https://github.com/g4s8/gitstrap/issues/44), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#44](https://github.com/g4s8/gitstrap/issues/44) assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), here is [why](https://www.0crat.com/footprint/CF7JL4282/6d1d9415-761e-4364-aabb-74f435f88f7c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by GnusinPavel** [comment]
@0crat wait for #45

**Comment by GnusinPavel** [comment]
@g4s8 @alex-semenyuk please close that ticket )

**Comment by GnusinPavel** [comment]
@0crat status

**Comment by GnusinPavel** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/g4s8/gitstrap/issues/44#issuecomment-669881165))

@GnusinPavel This is what I know about this job in CF7JL4282, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#44](https://github.com/g4s8/gitstrap/issues/44) is [in scope](http://www.zerocracy.com/policy.html#14) for 17days
  * The role is `DEV`
  * The job is assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk): This user reported the ticket
    * @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%2344%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
