### ISSUE TITLE
Organization spec

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#50]
Add commands for managing GitHub organizations:
 - [x] Specification
 - [x] Get command
 - ~[Create command~
 - [x] Apply command
 - ~Delete command~

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#50](https://github.com/g4s8/gitstrap/issues/50), since the job is not in scope anymore
