### ISSUE TITLE
gitstrap.go:136-140: Continue refactoring. Refactor...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/gitstrap#9]
The puzzle `5-6471c36f` from #5 has to be resolved: 

https://github.com/g4s8/gitstrap/blob/c054ddeb201472b0f15b09d40e3e12316231eef7/gitstrap.go#L136-L140

The puzzle was created by @g4s8 on 07-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#9](https://github.com/g4s8/gitstrap/issues/9) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/gitstrap/issues/9#issuecomment-504030151))

@g4s8 This is what I know about this job in [CF7JL4282](https://www.0crat.com/p/CF7JL4282), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#9](https://github.com/g4s8/gitstrap/issues/9) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @vassilevsky[/z](https://www.0crat.com/u/vassilevsky) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF7JL4282?q=%7Bjob%3A%27gh%3Ag4s8%2Fgitstrap%239%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@vassilevsky[/z](https://www.0crat.com/u/vassilevsky) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vassilevsky[/z](https://www.0crat.com/u/vassilevsky) resigned from [#9](https://github.com/g4s8/gitstrap/issues/9), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/gitstrap/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by vassilevsky** [comment]
@g4s8 could you assign it back to me please? ☺️

**Comment by g4s8** [comment]
@0crat assign @vassilevsky

**Comment by 0crat** [comment]
> @0crat assign @vassilevsky  ([here](https://github.com/g4s8/gitstrap/issues/9#issuecomment-506930452))

@g4s8 The job [#9](https://github.com/g4s8/gitstrap/issues/9) assigned to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), here is [why](https://www.0crat.com/footprint/CF7JL4282/17b58dcc-5701-4231-867a-2543c333a881); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by vassilevsky** [comment]
@g4s8 thank you 😘

**Comment by vassilevsky** [comment]
@0crat wait for PR improvements

**Comment by 0crat** [comment]
> @0crat wait for PR improvements ([here](https://github.com/g4s8/gitstrap/issues/9#issuecomment-506937197))

@vassilevsky The impediment for [#9](https://github.com/g4s8/gitstrap/issues/9) was registered successfully by @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by 0pdd** [comment]
The puzzle `5-6471c36f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#25](https://github.com/g4s8/gitstrap/issues/25) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vassilevsky[/z](https://www.0crat.com/u/vassilevsky), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#9](https://github.com/g4s8/gitstrap/issues/9) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vassilevsky[/z](https://www.0crat.com/u/vassilevsky)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#25](https://github.com/g4s8/gitstrap/issues/25) is solved here.
